Resources:
  ProcessQueryDataUploadSns:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: "Process query data upload"
      FifoTopic: False
      Subscription: 
        - 
          Endpoint: !GetAtt StartUploadQueryDataStepFunctionLambdaFunction.Arn
          Protocol: lambda
      TopicName: process-query-data-upload-${opt:stage}