Resources:
  CodeBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: sls-retrobase-frontend-CodeBuild-${opt:stage}
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
        Name: sls-retrobase
      Environment:
        Type: LINUX_CONTAINER    
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:3.0"
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub
          - >
            version: 0.2
            env:
              variables:
                  websiteUrl: '${websiteUrl}'
                  apiUrl: 'https://${QueryRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${opt:stage}/sls-retrobase-${opt:stage}'
            phases:
              pre_build:
                commands:
                  - echo List directory files...
                  - ls
                  - echo Installing source NPM dependencies...
                  - npm install
              build:
                commands:
                  - echo List active directory...
                  - ls
                  - echo Inserting Api Url into config.json from environment 
                  - node PutApiUrlConfig.js ${apiUrl} ${websiteUrl}
                  - echo Build started on `date`
                  - npm run build
              post_build:
                commands:
                  - echo List build directory...
                  - ls ./build
                  - > 
                    aws s3 cp --recursive --acl public-read ./build s3://${Website}
            artifacts:
              files:
                - '**/*'
          - apiUrl: !Join ['', [ "https://", !GetAtt QueryRestApi.RootResourceId, ".execute-api.us-east-1.amazonaws.com/dev/sls-retrobase-dev"]]
            websiteUrl: !GetAtt Website.WebsiteURL
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Effect: Allow
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /service-role/
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:GetBucketVersioning"
                  - "s3:PutObject"
                Resource: 
                  - !GetAtt PipelineBucket.Arn
                  - !Join ['', [!GetAtt PipelineBucket.Arn, "/*"]]
              - 
                Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:GetBucketVersioning"
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                Resource: 
                  - !GetAtt Website.Arn
                  - !Join ['', [!GetAtt Website.Arn, "/*"]]
              -
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "cloudfront:CreateInvalidation"
                Resource:
                  - "*"
    DependsOn: Website